### ISSUE TITLE
Summoner name with special characters

### ISSUE THREAD

**Issue by MontejoJorge** [MontejoJorge/riot.js#3]
`Unexpected token < in JSON at position 0` when search a summoner with an special character. For example: `Bôckchen`

**Comment by andrefpoliveira** [comment]
Hey! Could I try to solve this as part of Hacktoberfest? :)

**Comment by andrefpoliveira** [comment]
Hey ;) I started testing your system and I'm a little confused. I tried running the test file you have with "Kite Machine" and "Stor Olle", 2 of the best LoL players and I got a 200 response

Here is an image of the result. Maybe I understood something wrong? [Image](https://pasteboard.co/lfapUmpYwz3I.png)

**Comment by MontejoJorge** [comment]
I've been reviewing this, it looks like I was wrong about the source of the error. I think it comes from using names with special characters.

For example: `Bôckchen`.  This returns: `Unexpected token < in JSON at position 0`

**Comment by andrefpoliveira** [comment]
Ok thanks! I will then check that out ;)

**Comment by MontejoJorge** [comment]
A single line of code can fix a lot of things, thanks for your contribution! @andrefpoliveira

**Comment by andrefpoliveira** [comment]
@MontejoJorge thank you for the opportunity!
